#!/usr/bin/env python3
"""
Wekan MCP Credential Helper

Interactive tool to obtain and validate API credentials for the Wekan MCP server.

Usage:
    python setup_wekan.py              # Interactive credential capture
    python setup_wekan.py --validate   # Check current .env credentials
    python setup_wekan.py --config /opt/wekan-mcp/.env  # specify config path
"""
import argparse
import getpass
import os
import sys
import requests


def login(url, username, password):
    """Authenticate via POST /users/login and return token + user_id."""
    response = requests.post(
        f"{url}/users/login",
        json={"username": username, "password": password},
        timeout=10,
    )
    if response.status_code == 200:
        data = response.json()
        return data.get("token"), data.get("id")
    return None, None


def write_env(config_path, url, token, user_id):
    """Write credentials to .env at the specified path."""
    content = (
        f"# Wekan MCP Configuration\n"
        f"# Generated by setup_wekan.py\n"
        f"# To refresh: python setup_wekan.py\n\n"
        f"WEKAN_URL={url}\n"
        f"WEKAN_API_TOKEN={token}\n"
        f"WEKAN_USER_ID={user_id}\n"
    )
    with open(config_path, "w") as f:
        f.write(content)
    print(f".env written to {os.path.abspath(config_path)}")


def interactive():
    """Prompt for credentials and write .env."""
    print("=== Wekan MCP Credential Capture ===\n")
    url = input("Wekan URL (e.g., https://wekan.example.com): ").strip()
    if not url:
        print("Error: URL is required.")
        sys.exit(1)

    username = input("Username: ").strip()
    if not username:
        print("Error: Username is required.")
        sys.exit(1)

    # Issue #13: mask password input
    password = getpass.getpass("Password: ")
    if not password:
        print("Error: Password is required.")
        sys.exit(1)

    print("\nAuthenticating...")
    token, user_id = login(url, username, password)
    if token:
        print(f"Success! User ID: {user_id}")
        write_env(".env", url, token, user_id)
    else:
        print("Authentication failed. Check your credentials and URL.")
        sys.exit(1)


def validate(config_path):
    """Check if current .env credentials work."""
    if not os.path.isfile(config_path):
        print(f"Error: Config file not found: {config_path}")
        sys.exit(1)

    # Manual env parsing to avoid requiring python-dotenv as a runtime dep
    env = {}
    with open(config_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip()

    wekan_url = env.get("WEKAN_URL")
    token = env.get("WEKAN_API_TOKEN")
    user_id = env.get("WEKAN_USER_ID")

    if not all([wekan_url, token, user_id]):
        missing = [k for k in ("WEKAN_URL", "WEKAN_API_TOKEN", "WEKAN_USER_ID") if not env.get(k)]
        print(f"Error: {', '.join(missing)} not set in {config_path}")
        sys.exit(1)

    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(f"{wekan_url}/api/user", headers=headers, timeout=10)
    if resp.status_code == 200:
        user = resp.json()
        print(f"Valid! Logged in as: {user.get('username', 'unknown')}")
        print(f"Email: {user.get('email', 'N/A')}")
    else:
        print(f"Invalid: HTTP {resp.status_code}")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Wekan MCP Credential Helper")
    parser.add_argument("--validate", action="store_true", help="Validate current .env credentials")
    parser.add_argument("--config", default=".env", help="Path to .env config file (default: .env)")
    args = parser.parse_args()

    if args.validate:
        validate(args.config)
    else:
        interactive()
